_commit: v1.6.18-4-gf354859
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: pihole
helmRelease: pihole
helmRepo: https://mojo2600.github.io/pihole-kubernetes/
helmValues: helm/values.yaml
helmVersion: ''
ingress: false
labels: ''
name: pihole
namespace: pihole
pvc: false
reloader: true
resources:
- external-secrets.yaml
service: false
serviceAccount: false
upstreamURL: https://pi-hole.net
url: https://github.com/charlesthomas/homelab-pihole
