_commit: v1.9.0-1-g02b6330
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: ''
name: pihole
namespace: pihole
pvc: false
reloader: true
resources:
- namespaces.yaml
- configmaps.yaml
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- pvcs.yaml
- services.yaml
service: false
serviceAccount: false
upstreamURL: https://pi-hole.net
url: https://github.com/charlesthomas/homelab-pihole
