---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-pihole

resources:
- resources/namespaces.yaml
- resources/configmaps.yaml
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/pvcs.yaml
- resources/services.yaml

patches:
