---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-pihole

images:
  - name: pihole
    newName: pihole/pihole
    newTag: 2024.07.0

resources:
- resources/configmaps.yaml
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/services.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: pihole
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
