---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-pihole

resources:
- resources/namespaces.yaml
patches:
helmCharts:
- name: pihole
  namespace: pihole
  releaseName: pihole
  repo: https://mojo2600.github.io/pihole-kubernetes/
  valuesFile: helm/values.yaml
