---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-pihole

resources:
- resources/namespaces.yaml
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: pihole
      namespace: pihole
      annotations:
        gethomepage.dev/href: https://pihole.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: pihole
        gethomepage.dev/name: pihole
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
helmCharts:
- name: pihole
  namespace: pihole
  releaseName: pihole
  repo: https://mojo2600.github.io/pihole-kubernetes/
  valuesFile: helm/values.yaml
