---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-ftl
  namespace: pihole
  labels:
    app: pihole
data:
  pihole-FTL.conf: |
    MAXDBDAYS=60
    PRIVACYLEVEL=3
    IGNORE_LOCALHOST=yes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-custom-dnsmasq
  namespace: pihole
  labels:
    app: pihole
data:
  02-custom.conf: |
    addn-hosts=/etc/addn-hosts
  addn-hosts: |
  05-pihole-custom-cname.conf: |
