---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  labels:
    app: pihole
  name: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: "500Mi"
